modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/issues"
license = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/blob/1.16_Architectury/LICENCE.md"

[[mods]]
modId = "littlemaidmodelloader"
version = "${version}"
displayName = "LittleMaid ModelLoader"
credits = "Created by MMM, remixed by EMB4 & Verclene, patched by firis-games, remade by Sistr"
authors = "Sistr"
description = "メイドさんのモデルローダーです。"
logoFile = "icon.png"

[[dependencies.littlemaidmodelloader]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidmodelloader]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidmodelloader]]
modId = "architectury"
mandatory = true
versionRange = "[2.10.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.littlemaidmodelloader]]
modId = "cloth_config"
mandatory = true
versionRange = "[5.3.63,)"
ordering = "AFTER"
side = "BOTH"