modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/issues"
license = "https://github.com/SistrScarlet/LittleMaidModelLoader-Fabric/blob/1.16_Architectury/LICENCE.md"

[[mods]]
modId = "littlemaidmodelloader"
version = "${version}"
displayName = "LittleMaid ModelLoader"
credits = "Created by MMM, remixed by EMB4 & Verclene, patched by firis-games, remade by Sistr, some models created by voms"
authors = "Sistr"
description = "メイドさんのモデルローダーです。"
logoFile = "icon.png"

[[dependencies.littlemaidmodelloader]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidmodelloader]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.littlemaidmodelloader]]
modId = "architectury"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.littlemaidmodelloader]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.0.0,)"
ordering = "NONE"
side = "BOTH"